version: "3.8"

services:
  test-nginx:
    image: nginx:alpine
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.test-nginx.rule=Host(`example.com`)"
      - "traefik.http.routers.test-nginx.entrypoints=websecure"
      - "traefik.http.routers.test-nginx.tls.certresolver=letsencrypt"
      - "traefik.http.services.test-nginx.loadbalancer.server.port=80" # приложение должно слушать 80 порт!
    networks:
      - web
    restart: unless-stopped

networks:
  web:
    external: true
