services:
  db:
    networks:
      - sitenet
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=somewordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
      
  wp:
    networks:
      - sitenet
      - traefik-servicenet
    labels:
      - "traefik.enable=true"
      # .web - ключ можно заменить на любое другое название
      - "traefik.http.routers.web.entrypoints=web-secure"
      - "traefik.http.routers.web.rule=Host(`wp.invalid.example`)" # change hostname!
      - "traefik.http.routers.web.tls=true"
      - "traefik.http.routers.web.tls.certresolver=tlschallenge"
      - "traefik.http.routers.web.middlewares=traefik-compress,secHeaders@file"
      - "traefik.http.services.web.loadbalancer.server.port=80" # set port the container listenes to
    image: vasiliypolo/php:latest # https://hub.docker.com/_/wordpress/
    ports:
      - 6064:80 # change ip if required
    volumes:
      - /var/www/test:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
    depends_on:
      - db

  pma:
    image: phpmyadmin:latest  # https://hub.docker.com/_/phpmyadmin
    labels:
      - "traefik.enable=true"
      # .web - ключ можно заменить на любое другое название
      - "traefik.http.routers.webad.entrypoints=web-secure"
      - "traefik.http.routers.webad.rule=Host(`phpadmin.on-review.ru`)" # change hostname!
      - "traefik.http.routers.webad.tls=true"
      - "traefik.http.routers.webad.tls.certresolver=tlschallenge"
      - "traefik.http.routers.webad.middlewares=secHeaders@file"
      - "traefik.http.services.webad.loadbalancer.server.port=80" # set port the container listenes to
    networks:
      - sitenet
      - traefik-servicenet
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=root
      - UPLOAD_LIMIT=50M
    ports:
      - 8080:80
    volumes:
     - ./config/pma_php.ini:/usr/local/etc/php/conf.d/conf.ini
     - ./config/pma_config.php:/etc/phpmyadmin/config.user.inc.php

volumes:
  db_data:

networks:
  sitenet:
  traefik-servicenet:
    external: true